redditstats/reddit/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^partials/', include([
        url(r'^comment/', include([
            url(r'^top_short/$', views.TopShortComments.as_view(), name='top_short'),
            url(r'^top_questions/$', views.TopDailyQuestions.as_view(), name='top_questions'),
            url(r'^top_answers/$', views.TopDailyAnswers.as_view(), name='top_answers'),
        ], namespace='comment')),

        url(r'^user/', include([
            url(r'^top_questions/$', views.TopDailyQuestionAuthors.as_view(), name='top_questions'),
            url(r'^top_answers/$', views.TopDailyAnswerAuthors.as_view(), name='top_answers'),
            url(r'^post_count/$', views.TopPosterByCount.as_view(), name='post_count'),
            url(r'^post_score/$', views.TopPosterByScore.as_view(), name='post_score'),
            url(r'^comment_count/$', views.TopCommenterByCount.as_view(), name='comment_count'),
            url(r'^comment_score/$', views.TopCommenterByScore.as_view(), name='comment_score'),
        ], namespace='user')),
        url(r'^top_mentions/$', views.TopMentions.as_view(), name='top_mentions'),
        url(r'^mod_activity/$', views.ModActivity.as_view(), name='mod_activity'),
    ], namespace='partials')),
    url(r'^$', views.Dashboard.as_view(), name='dashboard'),
]

redditstats/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

import redditstats.reddit.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(redditstats.reddit.urls),)
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

redditstats/reddit/models.py
from django.db import models
from django.template.defaultfilters import truncatechars


class User(models.Model):
    username = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.username


class Subreddit(models.Model):
    api_id = models.CharField(max_length=64, unique=True)
    name = models.CharField(max_length=255)
    moderators = models.ManyToManyField(
        User, related_name='moderates', blank=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, related_name='posts')
    subreddit = models.ForeignKey(Subreddit, related_name='posts')
    created = models.DateTimeField()
    api_id = models.CharField(max_length=64, unique=True)
    permalink = models.CharField(max_length=255)
    url = models.URLField(null=True, blank=True)
    title = models.CharField(max_length=511)
    text = models.TextField(null=True, blank=True)
    html = models.TextField(null=True, blank=True)

    @property
    def short_title(self):
        return truncatechars(self.title, 100)

    @property
    def reddit_link(self):
        return f'https://reddit.com{self.permalink}'

    def __str__(self):
        return self.short_title


class PostSnapshot(models.Model):
    post = models.ForeignKey(Post, related_name='snapshots')
    created = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField()
    ups = models.IntegerField()
    downs = models.IntegerField()
    comment_count = models.IntegerField()

    def __str__(self):
        return f'{self.ups}'


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.ForeignKey(User, related_name='comments', null=True, blank=True)
    created = models.DateTimeField()
    api_id = models.CharField(max_length=64, unique=True)
    permalink = models.CharField(max_length=255)
    depth = models.IntegerField()
    parent = models.ForeignKey(
        'self', related_name='children', null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    html = models.TextField(null=True, blank=True)

    @property
    def reddit_link(self):
        return f'https://reddit.com{self.permalink}'

    def __str__(self):
        return self.api_id


class CommentSnapshot(models.Model):
    comment = models.ForeignKey(Comment, related_name='snapshots')
    created = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField()
    ups = models.IntegerField()
    downs = models.IntegerField()

    def __str__(self):
        return f'{self.ups}'

redditstats/reddit/views.py
import operator
from collections import defaultdict
from datetime import datetime, time, timedelta
from functools import reduce

from django.db.models import (
    F,
    Max,
    OuterRef,
    Subquery,
    Sum,
    Q,
    Case,
    When,
    IntegerField,
    DateTimeField,
)
from django.db.models.functions import Length
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

import pytz

from .models import (
    Comment,
    CommentSnapshot,
    PostSnapshot,
    Subreddit,
    User,
)

AUTO_MOD = 'AutoModerator'
WEEK_SECONDS = 60 * 60 * 24 * 7


class HomebrewingMixin(object):
    @staticmethod
    def subreddit():
        return Subreddit.objects.get(name='homebrewing')


class LatestMixin(object):
    @staticmethod
    def week_ago():
        today = pytz.UTC.localize(
            datetime.combine(timezone.now().date(), time.min))
        return today - timedelta(days=7)


def top_users(queryset, top_count=10):
    """Return authors with the highest aggregate score for the model"""
    top = defaultdict(lambda: 0)
    for author_id, score in queryset.values_list('author', 'score'):
        top[author_id] += score
    top_scores = []
    for user_id, total in top.items():
        if len(top_scores) < top_count or any(total > s for _, s in top_scores):  # noqa
            # Check if total is greater than any existing score.
            if len(top_scores) == top_count:
                # Pop off the least score and
                # add this score if we're at the max
                top_scores.sort(key=lambda s: s[1], reverse=True)
                top_scores = top_scores[:top_count-1] + [(user_id, total)]
            else:
                # Else just add it to the list.
                top_scores += [(user_id, total)]
    score_map = dict(top_scores)
    users = list(User.objects.filter(id__in=score_map.keys()))
    # Add the score to the user objects
    for u in users:
        u.score = score_map.get(u.id)
    users.sort(key=lambda user: user.score, reverse=True)
    return users


class LatestCommentsMixin(LatestMixin, HomebrewingMixin):
    def comments(self):
        subreddit = self.subreddit()
        comment_snaps = CommentSnapshot.objects.filter(
            comment__post__subreddit=subreddit,
            created__gte=self.week_ago())
        # Create a subquery with the most recent snapshots first.
        newest = comment_snaps.filter(
            comment=OuterRef('pk')).order_by('-created')

        comments = Comment.objects.filter(
            post__subreddit=subreddit,
            created__gte=self.week_ago(),
            author__isnull=False
        ).select_related('author')
        return comments.annotate(
            # Get the latest score for the snapshots.
            score=Subquery(newest.values('score')[:1]))


class LatestPostsMixin(LatestMixin, HomebrewingMixin):
    def posts(self):
        subreddit = self.subreddit()
        post_snaps = PostSnapshot.objects.filter(
            post__subreddit=subreddit,
            created__gte=self.week_ago())
        # Create a subquery with the most recent snapshots first.
        newest = post_snaps.filter(post=OuterRef('pk')).order_by('-created')
        
        posts = subreddit.posts.filter(
            created__gte=self.week_ago()).select_related('author')
        return posts.annotate(
            # Get the latest score for the snapshots.
            score=Subquery(newest.values('score')[:1]))


class TopQuestionsMixin(LatestCommentsMixin):
    def comments(self):
        return super(TopQuestionsMixin, self).comments().filter(
            parent__isnull=True,
            post__author__username=AUTO_MOD,
            post__title__startswith='Daily Q & A!',
        )


class TopAnswersMixin(LatestCommentsMixin):
    def comments(self):
        return super(TopAnswersMixin, self).comments().filter(
            parent__isnull=False,
            depth=1,
            post__author__username=AUTO_MOD,
            post__title__startswith='Daily Q & A!',
        )


class TopUsersMixin(LatestMixin, HomebrewingMixin):
    template_name = 'partials/user/top.html'
    page_size = 3

    def users(self):
        raise NotImplemented

    def get_context_data(self, **kwargs):
        return super(TopUsersMixin, self).get_context_data(
            users=self.users()[:self.page_size],
            **kwargs)


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopShortComments(LatestCommentsMixin, TemplateView):
    length_limitation = 150
    page_size = 4
    template_name = 'partials/comment/top_short.html'

    def get_context_data(self, **kwargs):
        comments = self.comments().annotate(
            length=Length('text'),
        ).filter(
            length__lt=self.length_limitation,
        ).order_by('-score')[:self.page_size]

        return super(TopShortComments, self).get_context_data(
            comments=comments,
            **kwargs)


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopDailyQuestions(TopQuestionsMixin, TemplateView):
    page_size = 10
    template_name = 'partials/comment/top_questions.html'

    def get_context_data(self, **kwargs):
        comments = self.comments().order_by('-score')[:self.page_size]
        return super(TopDailyQuestions, self).get_context_data(
            comments=comments,
            **kwargs)


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopDailyQuestionAuthors(TopQuestionsMixin, TopUsersMixin, TemplateView):
    def users(self):
        return top_users(self.comments())
    

@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopDailyAnswers(TopAnswersMixin, TemplateView):
    page_size = 6
    template_name = 'partials/comment/top_answers.html'

    def get_context_data(self, **kwargs):
        comments = self.comments().order_by('-score')[:self.page_size]
        return super(TopDailyAnswers, self).get_context_data(
            comments=comments,
            **kwargs)


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopDailyAnswerAuthors(TopAnswersMixin, TopUsersMixin, TemplateView):
    def users(self):
        return top_users(self.comments())


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopPosterByCount(TopUsersMixin, TemplateView):
    def users(self):
        return User.objects.exclude(username=AUTO_MOD).annotate(
            score=Sum(
                Case(
                    When(posts__created__gte=self.week_ago(), then=1),
                    output_field=IntegerField(),
                )
            )
        ).filter(score__isnull=False).order_by('-score')


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopPosterByScore(LatestPostsMixin, TopUsersMixin, TemplateView):
    def users(self):
        return top_users(self.posts().exclude(author__username=AUTO_MOD))


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopCommenterByCount(TopUsersMixin, TemplateView):
    def users(self):
        return User.objects.annotate(
            score=Sum(
                Case(
                    When(comments__created__gte=self.week_ago(), then=1),
                    output_field=IntegerField(),
                )
            )
        ).filter(score__isnull=False).order_by('-score')


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopCommenterByScore(LatestCommentsMixin, TopUsersMixin, TemplateView):
    def users(self):
        return top_users(self.comments())


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class TopMentions(LatestPostsMixin, LatestCommentsMixin, TemplateView):
    template_name = 'partials/mentions.html'
    mention_lookups = [
        ['RDWHAHB', ['RDWHAHB']],
        ['Peat Smoked Lager', [' peat', '-peat']],
        ['Sour', [' sour', 'sour ']],
        ['NEIPA', ['NEIPA']],
    ]

    def mentions(self, posts, comments, *terms):
        filters = reduce(
            operator.or_, [Q(text__icontains=t) for t in terms])
        post_f = filters | reduce(
            operator.or_, [Q(title__icontains=t) for t in terms])
        return posts.filter(post_f).count() + comments.filter(filters).count()

    def get_context_data(self, **kwargs):
        posts = self.posts()
        comments = self.comments()
        mentions = {
            key: self.mentions(posts, comments, *terms)
            for key, terms in self.mention_lookups
        }
        return super(TopMentions, self).get_context_data(
            mentions=mentions,
            **kwargs)


@method_decorator(cache_page(WEEK_SECONDS), name='dispatch')
class ModActivity(LatestMixin, HomebrewingMixin, TemplateView):
    template_name = 'partials/mod_activity.html'

    def get_context_data(self, **kwargs):
        mods = self.subreddit().moderators.exclude(username=AUTO_MOD)
        mods = mods.annotate(
            post_count=Sum(
                Case(
                    When(posts__created__gte=self.week_ago(), then=1),
                    output_field=IntegerField(),
                )
            ),
            latest_post=Max(
                Case(
                    When(posts__created__gte=self.week_ago(),
                         then=F('comments__created')),
                    output_field=DateTimeField(),
                )
            ),
            comment_count=Sum(
                Case(
                    When(comments__created__gte=self.week_ago(), then=1),
                    output_field=IntegerField(),
                )
            ),
            latest_comment=Max(
                Case(
                    When(comments__created__gte=self.week_ago(),
                         then=F('comments__created')),
                    output_field=DateTimeField(),
                )
            )
        ).filter(Q(comment_count__gt=0) | Q(post_count__gt=0))

redditstats/templates/subreddit/homebrewing.html
{% load staticfiles humanize %}
<!DOCTYPE html>
<html lang="en" style="" class=" js no-touch svg inlinesvg svgclippaths no-ie8compat">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <title>Homebrewing in Review</title>
  <link href="{% static 'foundation-6.4.2-custom/css/foundation.css' %}" media="screen" rel="stylesheet">
  <link href="{% static 'foundation-icons/foundation-icons.css' %}" media="screen" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
  <link href="{% static 'app.css' %}" media="screen" rel="stylesheet">
</head>

<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-105151456-1', 'auto');
  ga('send', 'pageview');

</script>

<section role="main" class="body">
  <div id="css-newspaper-page">
    <div id="masthead">
      <div class="">
        <p><strong>{% now "l" %}</strong> {% now "F j, Y" %}</p>
      </div>
      <h1 class="paper-title" style="font-size:6em;">The Lurking Gazette</h1>
    </div>

    <div class="remote-load" data-url="{% url 'partials:comment:top_short' %}"></div>
    <div class="grid-x grid-padding-x">
      <div class="small-8 cell" id="mainStory">
        <div class="figure">
          <a href="{{ image_url }}">
            <img src="{{ image_url }}.jpg" style="margin-bottom: 1em;">
          </a>
        </div>
        <h1><a href="{{ image_post.reddit_link }}">{{ image_post.title }}</a></h1>
        <p class="lead">{{ image_post.author.username }}, {{ image_post.created|date:"l" }}</p>

        <div class="grid-x grid-margin-x small-up-3">
          <div class="cell">
            <div class="card">
              <div class="card-divider">Asking the right stuff</div>
              <div class="card-section">
                <div class="remote-load" data-url="{% url 'partials:user:top_questions' %}"></div>
                <h6 class="subheader" style="font-size: 0.75em;">Q&A question score</h6>
              </div>
            </div>
          </div>
          <div class="cell">
            <div class="card">
              <div class="card-divider">Paying it forward</div>
              <div class="card-section">
                <div class="remote-load" data-url="{% url 'partials:user:top_answers' %}"></div>
                <h6 class="subheader" style="font-size: 0.75em;">Q&A answer score</h6>
              </div>
            </div>
          </div>
          <div class="cell">

            <div class="card">
              <div class="card-divider">Show-offs</div>
              <div class="card-section">
                <div class="remote-load" data-url="{% url 'partials:user:post_count' %}"></div>
                <h6 class="subheader" style="font-size: 0.75em;">Posts</h6>
              </div>
            </div>
          </div>
          <div class="cell">
            <div class="card">
              <div class="card-divider">The popular kids</div>
              <div class="card-section">
                <div class="remote-load" data-url="{% url 'partials:user:post_score' %}"></div>
                <h6 class="subheader" style="font-size: 0.75em;">Post score</h6>
              </div>
            </div>
          </div>
          <div class="cell">

            <div class="card">
              <div class="card-divider">Always around</div>
              <div class="card-section">
                <div class="remote-load" data-url="{% url 'partials:user:comment_count' %}"></div>
                <h6 class="subheader" style="font-size: 0.75em;">Comments</h6>
              </div>
            </div>
          </div>
          <div class="cell">
            <div class="card">
              <div class="card-divider">Look at all that karma</div>
              <div class="card-section">
                <div class="remote-load" data-url="{% url 'partials:user:comment_score' %}"></div>
                <h6 class="subheader" style="font-size: 0.75em;">Comment score</h6>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="small-4 cell">
        <div class="aside">
          <h4>Top Q&A Answers</h4>
          <p>Stand in awe and wonder of their helpfulness.</p>
          <div class="remote-load" data-url="{% url 'partials:comment:top_answers' %}"></div>
        </div>
      </div>
    </div>
    <hr>
    <div class="grid-x">
      <div class="large-auto cell">
        <div class="remote-load" data-url="{% url 'partials:top_mentions' %}"></div>
      </div>
    </div>
    <hr>
    <div class="grid-x grid-margin-x">
      <div class="small-8 cell">
        <h2><a href="#">Best essay answer of the week!</a></h2>

        <p>This week it's {{ essay_comment.author.username }} that has an eloquent way of making a point. You may want to grab a {{ beer_types|random }} while you digest this heavy prose.</p>

          <div class="three-col">
            {{ essay_comment.text|linebreaks }}
          </div>
      </div>
      <div class="small-4 cell">
        <h4>Tyrant Abuses</h4>
        <div class="remote-load" data-url="{% url 'partials:mod_activity' %}"></div>
      </div>
    </div>
    <hr>
    <p class="right"><a href="#">Back to top</a></p>
    <p class="paper-title">The Lurking Gazette <i class="fi-shield"></i></p>
    <br>
  </div>

</section>

<script src="{% static 'foundation-6.4.2-custom/js/vendor/jquery.js' %}"></script>
<script src="{% static 'foundation-6.4.2-custom/js/vendor/what-input.js' %}"></script>
<script src="{% static 'foundation-6.4.2-custom/js/vendor/foundation.js' %}"></script>
<script src="{% static 'remoteLoad.js' %}"></script>
</body>
</html>